### ISSUE TITLE
blosc_compress_ctx accepts compressor while blosc_compress does not

### ISSUE THREAD

**Issue by FrancescElies** [Blosc/python-blosc#124]
While having a look at a test failing on bloscpack, I saw the following:

`blosc_compress_ctx` accepts a `compressor string` passed as parameter. 
While `blosc_compress` the compressor parameter is missing, therefore I believe is ignored. It uses the value from [g_global_context](https://github.com/Blosc/python-blosc/blob/master/c-blosc/blosc/blosc.c#L1302-L1308) instead.

On one hand when releasing the gil the compress string is passed, but on the other hand `blosc_compress` is using the global context [blosc_extension.c lines of interest](https://github.com/Blosc/python-blosc/blob/master/blosc/blosc_extension.c#L215-L237). Is this intentional what am I missing?

**Comment by FrancescAlted** [comment]
Are you referring to C-Blosc or Python-Blosc?  As Python-Blosc [does include the `cname` parameter in `blosc_compress`](http://python-blosc.blosc.org/reference.html#blosc.compress) I am going to assume that you mean C-Blosc.  In that case, yes, that's completely intentional and the reason for this inconsistency is that the API grew organically through this years.  For C-Blosc2 I am planning a new API that should be more consistent (and hopefully simpler).

I am closing this, but feel free to reopen if necessary.

**Comment by FrancescElies** [comment]
Thanks for the answer, I refer to [compress_helper](https://github.com/Blosc/python-blosc/blob/master/blosc/blosc_extension.c#L190-L191) which is being used by blosc_compress, right?
In this case cname is only used when calling `blosc_compress_ctx` but I wonder, how is being passed to `blosc_compress` if `RELEASEGIL` is false?

**Comment by FrancescAlted** [comment]
Yep, [the `cname` codec is setting a global variable internally by the `blosc_set_compressor()`](https://github.com/Blosc/python-blosc/blob/master/blosc/blosc_extension.c#L204).  This is the usual way on how to set parameters in C-Blosc.
