### ISSUE TITLE
not determinist multi-threaded compression and blosc headers.

### ISSUE THREAD

**Issue by SmartAudioTools** [Blosc/python-blosc#236]
Hi, I'm developing [serializejson](https://smartaudiotools.github.io/serializejson), a python library for fast serialization and deserialization of complex Python objects in [JSON](http://json.org) highly compatible with [pickle](https://docs.python.org/3/library/pickle.html)

I use blosc in order to compress binary data before encoding in Base64 for json serialisation.
I need to have always the same json when I serialize same data for comparison, checking and versioning of jsons.

Sadly, when multi-threaded , the blosc compression is not determinist for big data, forcing me to use only one thread for compression and losing blosc's advantage over other libraries when compressing. 

for example, following code give an AssertionError when nb_thread > 1

    import blosc
    datas = bytes(range(256)) * 1200
    nb_thread  = 2
    blosc.set_nthreads(nb_thread)
    for i in range(20):
        compressed_blosc_1 = blosc.compress(datas , 1, cname="zstd", clevel=1)
        compressed_blosc_2 = blosc.compress(datas , 1, cname="zstd", clevel=1)
        assert compressed_blosc_1 == compressed_blosc_2

Is there a possibility of using blosc in multi-tread while maintaining deterministic behavior?

Otherwise i would like to use the  [python-zstandard](https://github.com/indygreg/python-zstandard) libray for compression wich is determinist even in multi-thread. Sadly your blosc library wich is much faster than python-zstandard for decompression is not able to decompress data compressed with python-zstandard library beacause of  unrecognised header. 
Is there an option to recognize or ignore the header of the data compressed with the python-zstandard library if we pass the name of the compression to blosc.decompress ? 

More generally, is it possible to have data compressed with blosc that does not use specific blosc headers, to have data that can still be readable in 10 years even if blosc is no longer maintained?

**Comment by FrancescAlted** [comment]
Hi.  Unfortunately it is not possible.  Blosc achieves efficient paralellism by letting the first thread that ends its part of the compression to write first in the output buffer, then the next thread to finish will write after that, and so on so forth; this is the way we can save precious copy time.  As there is no guarantee on the order of the sequence of completing times for every thread, it is essentially impossible to guarantee an order (except for the trivial case that you use 1 single thread, as you found out already).

Regarding compatibility with zstandard, unfortunately the answer is negative again.  Blosc is all about speed, and it makes a number of choices for compressing/decompressing that makes it difficult (if not impossible) to read other formats in order to decompress them faster than the original implementation.  At any rate, my guess is that it is going to be difficult for any codec to decompress faster than zstandard *when* it is required to use zstandard own format.

Regarding your last question, well, the Blosc format is completely open (see https://github.com/Blosc/c-blosc/blob/master/README_CHUNK_FORMAT.rst) so the idea is that, even if Blosc is going to be unmaintained in 10 years, anybody could produce a reader (even a writer!) for the format.  In any case, the Blosc team is confident that happy users will provide resources for, hopefully, at least 10 more years.

**Comment by SmartAudioTools** [comment]
Hello , 
Thank for your response . 
I was speaking about blosc with cname = zstd and zstandard compatibility . 
From my tests (beside) , for bytes len  between 32 and 8193,   blosc compression with cname = "zstd" differ from zstandard  only by adding a header of 24 bytes . And blosc decrompression is much faster.  
I did'nt investigate much more but my guess was that it could be possible to decompress bytes compressed with zstandard with blosc, given the codec name "zstd" to blosc.decompress.

    import blosc
    import zstandard
    import numpy
    for size in range(32,8193,1):
        blosc.set_nthreads(1)
        inst = numpy.random.randint(0,10,size)
        compressed_zstd_blosc = blosc.compress(inst, 1, cname="zstd", clevel=1)
        compressed_zstandard = zstandard.ZstdCompressor(level=1, threads=1).compress(inst)
        assert compressed_zstd_blosc[24:] == compressed_zstandard

**Comment by FrancescAlted** [comment]
Yes, I know what you was speaking about ;-).  Actually, there are a lot of things that differ in the why that blosc+zstd and plain zstd store the output.  For one thing, I see that you are directing blosc to use the shuffle filter, and I don't think python-zstandard activates this.  Then, blosc tends to split the inputs in smaller pieces, and then again, this is not something that python-zstandard does.  Really, even if blosc and zstd both use the same codec internally, a lot is changing on how the output is created.

**Comment by SmartAudioTools** [comment]
Sad, so it's just a coincidence if blocks + zstd and zstandard are compatible for random bytes of length between 32 and 8193 ? I don't necessary want to use the shuffle filter . Maybe I should split my bytes into blocks of 8192 elements to keep this compatibility between blosc+zstd and standard ?
